# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 867902eb14ea0fc6d86137a2d852ea3268d9d2be47a655551fc2f41e9690a689f8132518c90afadd0e355076675c7b597f6e818ffad3d77ced9517fc270cea74

test:
  secret_key_base: 8c5b206e59c86599ec2cdd610052e688a78dfb88cdfd9423f49b2652d3d4405a54818140705e4d43f304971ed33f43d7213f01690aded226aea1430b1c57a143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
